---
# tasks file for hankkeet_visualisointi

- name: Deploy repos from git
  git:
    repo: "{{ item.repo }}"
    dest: "{{ static_site_dir }}/{{ item.subdir|default('') }}"
    version: "{{ item.version|default('HEAD') }}"
  with_items: static_site_config
